device: 'cuda:1'
amp: True
pin_memory: True
non_blocking: True
prefetch: False

checkpoint_load:
checkpoint_save:
log:
dataset_path: './data'
dataset: 'cifar10'

epochs: 1000
batch_size: 256
num_workers: 4
lr_un: 0.0001
lr_ft: 0.01
lr_scheduler: CosineAnnealingLR
model: 'preactresnet18'


client_optimizer: 'sgd'
sgd_momentum: 0.9 
wd: 5.0e-5
frequency_save: 0
random_seed: 0
ratio: 0.05
index: 

m: 0.7
ft_epoch: 20

r: 0.05
alpha: 0.7

layer_type: conv

result_file: cifar10_preactresnet18_badnet_0_1
clean_file: cifar10_preactresnet18_prototype

model_type: bd
data_type: clean_val

record_layer: layer4.1.conv2.weight
# record_layer: features.49.weight